import { useEffect, useMemo, useRef, useState } from 'react'
import ReactECharts from 'echarts-for-react'
import { scenarios } from './mock/scenarios'
import type { Scenario, ScenarioKey, Stage } from './types'

const Icon = ({ name, size = 18 }: { name: string; size?: number }) => {
  const paths: Record<string, string> = {
    cube:'M12 2 3 7l9 5 9-5-9-5Zm-9 5v10l9 5V12M21 7v10l-9 5', chip:'M9 3v3m6-3v3m-6 12v3m6-3v3M3 9h3m-3 6h3m12-6h3m-3 6h3M7 7h10v10H7z', activity:'M3 12h4l2-6 4 12 2-6h6', target:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0-4a5 5 0 1 0 0-10 5 5 0 0 0 0 10Zm0-4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z', sliders:'M4 7h10m4 0h2M4 17h2m4 0h10M14 4v6M6 14v6', play:'m9 7 7 5-7 5V7Z', download:'M12 3v12m-5-5 5 5 5-5M5 21h14', check:'m5 12 4 4L19 6', layers:'M12 3 3 8l9 5 9-5-9-5Zm-9 10 9 5 9-5m-18 5 9 5 9-5', network:'M12 5v4m-7 6v4m14-4v4M5 15h14M5 15l7-6 7 6M12 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4ZM5 19a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm14 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z', alert:'M12 9v4m0 4h.01M10.3 3.8 2.4 18a2 2 0 0 0 1.7 3h15.8a2 2 0 0 0 1.7-3L13.7 3.8a2 2 0 0 0-3.4 0Z', arrow:'m9 18 6-6-6-6', database:'M4 6c0 2 16 2 16 0S4 4 4 6Zm0 0v6c0 2 16 2 16 0V6m-16 6v6c0 2 16 2 16 0v-6', menu:'M4 6h16M4 12h16M4 18h16'
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] || paths.cube}/></svg>
}

const stageText: Record<Stage,string> = {IDLE:'等待配置',CHECKING:'检查输入与约束',SIMULATING:'执行方案仿真',OPTIMIZING:'搜索候选方案',VALIDATING:'验证性能与 SLO',COMPLETED:'规划完成'}
const stages: Stage[] = ['CHECKING','SIMULATING','OPTIMIZING','VALIDATING','COMPLETED']
const caseFeatures: Record<ScenarioKey,string[]> = {
  rag:['峰值 12.8K req/s','前缀复用 68%','平均 8.4 轮'],
  long:['64K+ 上下文','前缀复用 47%','平均 14.6 轮'],
  coding:['峰值 7.6K req/s','7.8 工具/任务','前缀复用 61%'],
}

function App() {
  const [scenarioKey,setScenarioKey] = useState<ScenarioKey>('rag')
  const [workspace,setWorkspace] = useState<'overview'|'input'|'optimization'|'results'>('overview')
  const [stage,setStage] = useState<Stage>('IDLE')
  const [progress,setProgress] = useState(0)
  const [scale,setScale] = useState(1)
  const timer = useRef<number | null>(null)
  const contentScroll = useRef<HTMLDivElement>(null)
  const scenario = scenarios[scenarioKey]

  useEffect(()=>()=>{ if(timer.current) window.clearInterval(timer.current) },[])
  useEffect(()=>{ contentScroll.current?.scrollTo({top:0}) },[workspace,scenarioKey])
  const startSimulation = () => {
    if(timer.current) window.clearInterval(timer.current)
    setWorkspace('optimization'); setStage('CHECKING'); setProgress(3)
    let p = 3
    timer.current = window.setInterval(()=>{
      p += p < 18 ? 3 : p < 74 ? 2 : 4
      if(p >= 100){ p=100; setStage('COMPLETED'); if(timer.current) window.clearInterval(timer.current) }
      else if(p < 18) setStage('CHECKING')
      else if(p < 38) setStage('SIMULATING')
      else if(p < 86) setStage('OPTIMIZING')
      else setStage('VALIDATING')
      setProgress(p)
    },120)
  }

  return <div className="app-shell">
    <Header/>
    <aside className="sidebar">
      <div className="side-kicker">AGENT 业务案例</div>
      <div className="case-list">{(Object.keys(scenarios) as ScenarioKey[]).map((key,i)=>{const item=scenarios[key];return <button key={key} className={`case-item ${scenarioKey===key?'active':''}`} onClick={()=>{setScenarioKey(key);setStage('IDLE');setProgress(0)}}>
        <div className="case-card-head"><span className="case-icon"><Icon name={key==='rag'?'database':key==='long'?'layers':'cube'}/></span><span><small className="case-index">CASE 0{i+1}</small><b>{item.name}</b></span><i/></div><p>{item.short}</p><div className="case-tags">{caseFeatures[key].map(x=><span key={x}>{x}</span>)}</div>
      </button>})}</div>
      <div className="side-divider"/>
      <button className="start-button" onClick={startSimulation}><span className="start-icon"><Icon name="play"/></span><span>开始仿真规划<small>参数空间探索与性能验证</small></span><Icon name="arrow" size={14}/></button>
    </aside>
    <main className="main">
      <div className="workspace-tabs">
        <button className={workspace==='overview'?'active':''} onClick={()=>setWorkspace('overview')}>工作流总览</button>
        <button className={workspace==='input'?'active':''} onClick={()=>setWorkspace('input')}>输入配置</button>
        <button className={workspace==='optimization'?'active':''} onClick={()=>setWorkspace('optimization')}>仿真寻优</button>
        <button className={workspace==='results'?'active':''} onClick={()=>stage==='COMPLETED'&&setWorkspace('results')}>规划结果 {stage==='COMPLETED'&&<i/>}</button>
      </div>
      <div className="content-scroll" ref={contentScroll}>
        {workspace==='overview' && <WorkflowOverview onStart={()=>setWorkspace('input')}/>} 
        {workspace==='input' && <UnifiedInput scenarioKey={scenarioKey}/>} 
        {workspace==='optimization' && <OptimizationWorkspace scenarioKey={scenarioKey} stage={stage} progress={progress} scale={scale} setScale={setScale} onStart={startSimulation} onViewResults={()=>setWorkspace('results')}/>}
        {workspace==='results' && <Results stage={stage} progress={progress} scenarioKey={scenarioKey}/>}
      </div>
    </main>
    <footer className="statusbar"><span><i className="ok-dot"/>配置完整度 <b>100%</b></span><span>场景 <b>{scenario.name}</b></span><span>资源 <b>{scenario.nodes} 节点 · {scenario.gpuCount} {scenario.gpu.split(' ')[0]}</b></span><span className={`run-state ${stage.toLowerCase()}`}><i/>{stageText[stage]}</span><span className="status-right"><Icon name="check" size={15}/>未发现约束冲突</span></footer>
  </div>
}

function Header(){
  return <header className="header"><div className="brand-mark"><span/><span/><span/></div><div className="brand"><h1>算存网一体化规划仿真平台</h1><p>INTEGRATED COMPUTING · STORAGE · NETWORK PLANNING SIMULATION PLATFORM</p></div><div className="header-context"><button className="ghost-button"><Icon name="download" size={16}/>导出方案</button></div></header>
}

function WorkflowOverview({onStart}:{onStart:()=>void}){
  const steps=[
    {n:'01',title:'业务输入',sub:'INPUT',icon:'cube',desc:'定义规划对象、资源边界、业务请求特征和目标约束。',items:['模型与软件栈','硬件与组网拓扑','请求与前缀特征','SLO 与资源上限']},
    {n:'02',title:'参数决策',sub:'DECISION',icon:'sliders',desc:'在四大类、七个全局参数维度中生成并决策候选配置。',items:['服务控制 · 服务级调度','推理执行 · 引擎 / 并行 / KV 复用','资源布局 · 部署亲和 / KV 资源池','数据移动 · 数据流编排']},
    {n:'03',title:'方案仿真',sub:'SIMULATION',icon:'activity',desc:'仿真候选配置，验证性能目标、资源约束并识别瓶颈。',items:['候选方案实例化','算子与网络流仿真','SLO 与资源校验','瓶颈定位与方案筛选']},
    {n:'04',title:'规划输出',sub:'OUTPUT',icon:'target',desc:'输出推荐规划方案及其性能表现和主要瓶颈。',items:['P/D 实例数量与配比','HBM / DDR / SSD 容量','网络与数据流方案','性能表现与瓶颈']},
  ]
  return <div className="page overview-page"><PageTitle eyebrow="WORKFLOW OVERVIEW" title="算存网一体化规划工作流" desc="从 Agent 业务需求出发，经过方案生成与仿真评估，形成可验证的资源规划方案。" badge="4 阶段 · 1 条闭环"/>
    <div className="workflow-map">{steps.map((x,i)=><div className="workflow-stage" key={x.n}><div className="stage-number">{x.n}</div><div className="stage-icon"><Icon name={x.icon} size={23}/></div><span>{x.sub}</span><h2>{x.title}</h2><p>{x.desc}</p><div>{x.items.map(item=><b key={item}><Icon name="check" size={12}/>{item}</b>)}</div>{i<steps.length-1&&<em><Icon name="arrow" size={20}/></em>}</div>)}</div>
    <div className="workflow-bottom"><div><span>规划逻辑</span><b>输入定义问题边界</b><Icon name="arrow"/><b>寻优过程决策参数</b><Icon name="arrow"/><b>仿真验证候选方案</b><Icon name="arrow"/><b>输出可执行规划</b></div><button onClick={onStart}>进入输入配置 <Icon name="arrow" size={15}/></button></div>
  </div>
}

function UnifiedInput({scenarioKey}:{scenarioKey:ScenarioKey}){
  const s=scenarios[scenarioKey]
  const hbmTB=(s.gpuCount*64/1024).toFixed(1)
  const flowObjects=scenarioKey==='rag'?'Prefix KV · P/D Handoff · Prefetch':scenarioKey==='long'?'Long KV · P/D Handoff · Tier Migration':'Branch KV · Tool Context · Prefetch'
  const option=useMemo(()=>({
    grid:{left:30,right:10,top:16,bottom:22},
    xAxis:{type:'category',data:s.load.map((_,i)=>`${i}:00`),axisLabel:{color:'#587087',interval:5,fontSize:8},axisLine:{lineStyle:{color:'#24364c'}},axisTick:{show:false}},
    yAxis:{type:'value',max:100,axisLabel:{show:false},splitLine:{lineStyle:{color:'#182a3e'}}},
    series:[{type:'line',data:s.load,smooth:.35,symbol:'none',lineStyle:{width:2,color:'#38bdf8'},areaStyle:{color:{type:'linear',x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:'rgba(56,189,248,.3)'},{offset:1,color:'rgba(56,189,248,.01)'}]}}}]
  }),[s])
  return <div className="page unified-input"><PageTitle eyebrow="PLANNING INPUT" title={`${s.name} · 输入配置`} desc="在同一页面确认模型、硬件资源、业务负载以及规划目标。" badge="输入检查通过"/>
    <div className="input-overview-strip"><span><i>01</i><b>模型与软件栈</b><small>{s.model}</small></span><Icon name="arrow"/><span><i>02</i><b>硬件资源</b><small>{s.gpuCount} × {s.gpu}</small></span><Icon name="arrow"/><span><i>03</i><b>业务负载</b><small>{s.peak.toLocaleString()} req/s Peak</small></span><Icon name="arrow"/><span><i>04</i><b>目标约束</b><small>TTFT / TPOT / Cost</small></span></div>
    <div className="unified-grid">
      <Card title="01 · 模型与推理软件栈" subtitle="MODEL & SOFTWARE STACK" icon="cube"><div className="model-profile"><div className="model-identity"><div className="model-symbol">{scenarioKey==='rag'?'Q3':scenarioKey==='long'?'DS':'DC'}</div><div><small>当前模型</small><h2>{s.model}</h2><p>{s.modelSize} · MoE Architecture</p></div><span><Icon name="check" size={13}/>模型参数已校验</span></div><div className="model-specs"><Field label="模型层数" value="80" unit="Layers"/><Field label="Hidden Size" value="8,192"/><Field label="Query Heads" value="64"/><Field label="KV Heads" value="8"/><Field label="Attention" value="GQA / Dense"/><Field label="MoE 结构" value="64 Experts / Top-2"/><Field label="Weight / Activation" value="BF16 / BF16"/><Field label="KV dtype" value="FP16"/></div></div><div className="stack-line"><span>{s.framework}<small>推理框架</small></span><i/><span>{s.runtime}<small>加速运行时</small></span><i/><span>{s.comm}<small>集合通信库</small></span><i/><span>服务控制 · 推理执行 · 资源布局 · 数据移动<small>规划能力边界</small></span></div></Card>
      <Card title="02 · 硬件与资源拓扑" subtitle="A5 SUPERNODE · MEMORY FABRIC · HIERARCHICAL KV STORAGE" icon="chip"><div className="hardware-resource-bar"><Metric icon="chip" label="计算资源" value={`${s.nodes}`} unit={`节点 · ${s.gpuCount} 卡`}/><Metric icon="database" label="L0 · HBM" value={hbmTB} unit="TB · 64 GB/卡"/><Metric icon="layers" label="L1 · DDR Pool" value={`${s.ddrTB}`} unit="TB · 跨节点"/><Metric icon="database" label="L2 · Local SSD" value={`${s.localSsdTB}`} unit="TB · 双集群"/><Metric icon="database" label="L3 · Remote SSD" value={`${s.remoteSsdTB}`} unit="TB · 跨集群"/><Metric icon="network" label="互联资源池" value="4" unit="Rails · Dual Plane"/></div><InputNetworkTopology scenario={s}/></Card>
      <Card title="03 · 业务负载特征" subtitle="REQUEST · PREFIX · DATA MOVEMENT" icon="activity"><div className="unified-workload"><div><div className="module-subtitle"><span>请求规模特征</span><small>24H REQUEST PROFILE</small></div><div className="inline-kpis"><MiniMetric label="峰值请求" value={s.peak.toLocaleString()} unit="req/s"/><MiniMetric label="平均请求" value={s.average.toLocaleString()} unit="req/s"/><MiniMetric label="会话轮数" value={s.turns} unit="avg"/><MiniMetric label="工具调用" value={s.toolCalls} unit="/task"/></div><ReactECharts option={option} style={{height:178}}/></div><div><div className="module-subtitle"><span>前缀共享与演化特征</span><small>SHARING & EVOLUTION</small></div><div className="compact-prefix"><div>{s.prefixItems.slice(0,4).map(x=><p key={x.label}><span>{x.label}</span><b><i style={{width:`${x.value}%`}}/></b><strong>{x.value}%</strong></p>)}</div><div className="compact-evolution">{s.evolution.map(x=><span key={x.round} className={x.type}><i/>{x.round}<small>{x.action}</small></span>)}</div></div></div></div><div className="flow-input-strip"><span><small>业务数据对象</small><b>{flowObjects}</b></span><span><small>数据移动范围</small><b>P / D · HBM / DDR / SSD</b></span><span><small>传输语义</small><b>关键路径 · 后台迁移 · 容错</b></span></div></Card>
      <Card title="规划目标与约束" subtitle="OBJECTIVES & CONSTRAINTS" icon="target"><div className="goal-strip"><Objective label="TTFT P95" value={`${s.ttftTarget}`} unit="ms"/><Objective label="TPOT P95" value={`${s.tpotTarget}`} unit="ms"/><Objective label="目标吞吐" value={`${s.throughputTarget.toFixed(1)}`} unit="M token/s"/><Objective label="设备上限" value={`${s.gpuCount}`} unit="Cards"/></div></Card>
    </div>
  </div>
}

function InputNetworkTopology({scenario}:{scenario:Scenario}){
  return <div className="kv-topology"><div className="network-caption"><span>分层存储与异构传输资源拓扑</span><b>DUAL CLUSTER · MULTI-RAIL · CROSS-CLUSTER</b></div><svg viewBox="0 0 1120 590" role="img" aria-label="双 A5 超节点集群 KV Cache 分层存储网络拓扑">
    <defs><linearGradient id="clusterFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0d2438"/><stop offset="1" stopColor="#091827"/></linearGradient><linearGradient id="hbmFill" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stopColor="#0e7296"/><stop offset="1" stopColor="#12415d"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="2.4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
    <g className="topology-backbone"><rect x="390" y="12" width="150" height="44" rx="5"/><rect x="580" y="12" width="150" height="44" rx="5"/><text x="465" y="30">FABRIC PLANE A</text><text x="465" y="44" className="sub">RDMA / RoCE · RAIL 0 / 2</text><text x="655" y="30">FABRIC PLANE B</text><text x="655" y="44" className="sub">RDMA / RoCE · RAIL 1 / 3</text><path d="M390 34H335V88M540 34H558M580 34H562M730 34H785V88"/><circle cx="560" cy="34" r="3"/></g>
    <path className="intercluster" d="M520 93H600"/><text className="link-label" x="560" y="84">双平面集群互联</text>
    <g className="cluster-box"><rect x="18" y="76" width="502" height="374" rx="9" fill="url(#clusterFill)"/><rect x="600" y="76" width="502" height="374" rx="9" fill="url(#clusterFill)"/><text className="cluster-title" x="40" y="103">CLUSTER A · A5 超节点集群</text><text className="cluster-meta" x="495" y="103" textAnchor="end">{Math.floor(scenario.nodes/2)} Nodes · Local KV Domain</text><text className="cluster-title" x="830" y="103">CLUSTER B · A5 超节点集群</text><text className="cluster-meta" x="1077" y="103" textAnchor="end">{Math.ceil(scenario.nodes/2)} Nodes · Local KV Domain</text></g>
    <g className="gateway"><rect x="308" y="77" width="54" height="28" rx="4"/><text x="335" y="95">GW-A</text><rect x="758" y="77" width="54" height="28" rx="4"/><text x="785" y="95">GW-B</text></g>
    <g className="supernode"><rect x="42" y="124" width="218" height="104" rx="6"/><rect x="278" y="124" width="218" height="104" rx="6"/><rect x="624" y="124" width="218" height="104" rx="6"/><rect x="860" y="124" width="218" height="104" rx="6"/><text x="58" y="146">A5 SUPERNODE A1</text><text x="294" y="146">A5 SUPERNODE A2</text><text x="640" y="146">A5 SUPERNODE B1</text><text x="876" y="146">A5 SUPERNODE B2</text>{[58,105,152,199,294,341,388,435,640,687,734,781,876,923,970,1017].map((x,i)=><rect className="compute-chip" key={x} x={x} y="160" width="32" height="25" rx="3"/>)}{[58,294,640,876].map((x,i)=><g key={x}><rect className="hbm-tier" x={x} y="195" width="184" height="21" rx="3" fill="url(#hbmFill)"/><text className="tier-text" x={x+92} y="209">L0 · HBM KV · 64 GB/Card</text></g>)}</g>
    <g className="memory-lines"><path d="M151 228V258M387 228V258M733 228V258M969 228V258"/><path d="M151 242H387M733 242H969"/><text className="backend-label" x="269" y="237">UB · PCIe DMA / Host Staging</text><text className="backend-label" x="851" y="237">UB · PCIe DMA / Host Staging</text></g>
    <g className="ddr-pool"><rect x="42" y="258" width="454" height="65" rx="6"/><rect x="624" y="258" width="454" height="65" rx="6"/><text x="62" y="281">L1 · DDR KV POOL · 跨节点共享</text><text x="476" y="281" textAnchor="end" className="capacity">{scenario.ddrTB/2} TB</text><text x="62" y="302" className="sub">A1 ⇄ A2 高速内存互联 · Global Addressing in Cluster A</text><text x="644" y="281">L1 · DDR KV POOL · 跨节点共享</text><text x="1058" y="281" textAnchor="end" className="capacity">{scenario.ddrTB/2} TB</text><text x="644" y="302" className="sub">B1 ⇄ B2 高速内存互联 · Global Addressing in Cluster B</text></g>
    <g className="storage-lines"><path d="M269 323V346"/><path d="M851 323V346"/><text className="backend-label storage" x="269" y="339">NVMe / Storage Backend</text><text className="backend-label storage" x="851" y="339">NVMe / Storage Backend</text></g>
    <g className="local-ssd"><rect x="42" y="346" width="454" height="73" rx="6"/><rect x="624" y="346" width="454" height="73" rx="6"/><text x="62" y="370">L2 · LOCAL SSD KV POOL A</text><text x="476" y="370" textAnchor="end" className="capacity">{scenario.localSsdTB/2} TB</text><text x="62" y="391" className="sub">集群内共享 · NVMe-oF · 16 GB/s · 2.1M IOPS</text><text x="62" y="406" className="sub">HBM / DDR 淘汰落盘与 Prefetch 回源</text><text x="644" y="370">L2 · LOCAL SSD KV POOL B</text><text x="1058" y="370" textAnchor="end" className="capacity">{scenario.localSsdTB/2} TB</text><text x="644" y="391" className="sub">集群内共享 · NVMe-oF · 16 GB/s · 2.1M IOPS</text><text x="644" y="406" className="sub">HBM / DDR 淘汰落盘与 Prefetch 回源</text></g>
    <g className="remote-lines"><path d="M269 419V480H425"/><path d="M851 419V480H695"/><circle cx="269" cy="448" r="3"/><circle cx="851" cy="448" r="3"/></g><text className="link-label" x="326" y="472">NVMe-oF / RDMA Storage</text><text className="link-label" x="794" y="472">NVMe-oF / RDMA Storage</text>
    <g className="remote-ssd"><rect x="425" y="458" width="270" height="76" rx="7"/><text x="445" y="482">L3 · REMOTE SSD KV POOL</text><text x="675" y="482" textAnchor="end" className="capacity">{scenario.remoteSsdTB} TB</text><text x="445" y="504" className="sub">跨集群共享 · Global KV Index</text><text x="445" y="519" className="sub">Cluster A ⇄ Cluster B · RDMA Fabric</text></g>
    <g className="tier-legend"><circle cx="28" cy="552" r="4"/><text x="40" y="556">L0 HBM · 超节点本地</text><circle cx="28" cy="574" r="4"/><text x="40" y="578">L1 DDR · 跨节点</text><circle cx="216" cy="552" r="4"/><text x="228" y="556">L2 SSD · 集群内</text><circle cx="216" cy="574" r="4"/><text x="228" y="578">L3 SSD · 跨集群</text></g>
  </svg></div>
}

const getKvResourceStack=(s:Scenario)=>s.framework.startsWith('vLLM')?'LMCache + Mooncake Store':'Native KV Manager + Mooncake Store'

const getDecisionCategories=(s:Scenario)=>{
  const kvStack=getKvResourceStack(s)
  return [
  {group:'服务控制层',name:'服务级调度',icon:'network',items:'请求准入 · 实例路由 · P-D Pairing',search:'实例路由 / P-D Pairing / 准入策略',evaluate:'服务排队 · 缓存命中 · SLO',value:'Load-aware · Cache-aware Routing',detail:'Affinity · P-D Pairing · Admission Control'},
  {group:'推理执行层',name:'推理引擎调度',icon:'activity',items:'Batch Size · Chunk Size · 实例内调度',search:'Batch / Chunk / 调度策略组合',evaluate:'排队时延 · 设备利用率',value:'Continuous Batching',detail:`max_seqs ${Math.round(s.maxConcurrency/s.nodes)} · Chunk 4K`},
  {group:'推理执行层',name:'并行策略',icon:'layers',items:'TP · DP · EP · PP',search:'TP / DP / EP / PP 组合',evaluate:'计算效率 · 通信开销',value:'TP 8 · DP 4 · EP 8',detail:'PP 1 · P/D 独立配置'},
  {group:'推理执行层',name:'KV 复用与缓存策略',icon:'cube',items:'Prefix Cache · 准入 · 淘汰 · Prefetch',search:'复用 / 准入 / 淘汰 / 预取组合',evaluate:'前缀复用收益 · 回源开销',value:'Prefix Cache · Adaptive Prefetch',detail:'Cache Admission · Cost-aware LRU'},
  {group:'资源布局层',name:'部署拓扑与资源亲和',icon:'chip',items:'实例数量 · P/D 配比 · 拓扑亲和',search:'P/D 配比 / 实例放置 / NUMA-Rail 亲和',evaluate:'跨节点开销 · 负载均衡 · 通信局部性',value:`P-D 分离 · ${s.prefillNodes}:${s.decodeNodes}`,detail:`${s.prefillNodes}P / ${s.decodeNodes}D 节点 · Topology-aware Pairing`},
  {group:'资源布局层',name:'KV 资源池与分层放置',icon:'database',items:'管理组件 · 池化范围 · 分层放置 · 迁移',search:'LMCache / HiCache / Mooncake 与池化方案',evaluate:'容量成本 · 复用收益 · 搬运开销',value:'分层全局 KV 资源池',detail:`${kvStack} · HBM ↔ DDR ↔ SSD`},
  {group:'数据移动层',name:'数据流编排',icon:'network',items:'Backend · Slice · Rail · Priority',search:'Backend / Slice / Rail / Priority',evaluate:'链路竞争 · 传输时延',value:'Backend · Slice · Rail · Priority',detail:'Topology-aware · Dynamic Remap'},
  ]
}
const decisionGroupOrder=['服务控制层','推理执行层','资源布局层','数据移动层']
const decisionPoints=Array.from({length:7},(_,i)=>{const angle=i*Math.PI*2/7-Math.PI/2;return{x:115+Math.cos(angle)*96,y:115+Math.sin(angle)*96}})

function OptimizationWorkspace({scenarioKey,stage,progress,scale,setScale,onStart,onViewResults}:{scenarioKey:ScenarioKey;stage:Stage;progress:number;scale:number;setScale:(n:number)=>void;onStart:()=>void;onViewResults:()=>void}){
  const decisionCategories=getDecisionCategories(scenarios[scenarioKey])
  const isRunning=stage!=='IDLE'&&stage!=='COMPLETED'
  const iteration=stage==='IDLE'?0:Math.min(25,Math.max(1,Math.ceil(progress/4)))
  return <div className="page optimization-page"><PageTitle eyebrow="SIMULATION & OPTIMIZATION" title="参数空间寻优与方案仿真" desc="在候选空间中持续生成配置、仿真性能并筛选可行方案，最终形成推荐规划结果。" badge={stageText[stage]}/>
    <div className="optimization-layout"><section className="decision-panel"><div className="panel-title"><div><h3>可调参数空间</h3><p>PARAMETER DIMENSIONS</p></div><span>4 GROUPS · 7 DIMENSIONS</span></div><div className="decision-list grouped">{decisionGroupOrder.map(group=><section className="decision-group" key={group}><div className="decision-group-head"><span>{group}</span><small>{decisionCategories.filter(x=>x.group===group).length} DIM</small></div>{decisionCategories.filter(x=>x.group===group).map(x=>{const i=decisionCategories.findIndex(item=>item.name===x.name);return <div key={x.name} className={`decision-item ${isRunning?'coupled':''} ${stage==='COMPLETED'?'decided':''}`}><span className="decision-icon"><Icon name={x.icon}/></span><div><small>DIM 0{i+1} · {x.name}</small><b>{stage==='COMPLETED'?x.value:isRunning?x.search:x.items}</b><p>{stage==='COMPLETED'?x.detail:isRunning?x.evaluate:'典型可调项'}</p></div><i>{stage==='COMPLETED'?<Icon name="check" size={13}/>:isRunning?<span/>:'···'}</i></div>})}</section>)}</div></section>
      <section className="optimization-stage"><div className={`decision-orbit ${isRunning?'coupling':''} ${stage==='COMPLETED'?'converged':''}`}><svg className="coupling-network" viewBox="0 0 230 230">{decisionPoints.map((point,i)=><line className="radial" key={`r-${i}`} x1="115" y1="115" x2={point.x} y2={point.y}/>)}{decisionPoints.map((point,i)=>{const next=decisionPoints[(i+1)%decisionPoints.length];return <line className="chord" key={`c-${i}`} x1={point.x} y1={point.y} x2={next.x} y2={next.y}/>})}{decisionPoints.map((point,i)=>{const next=decisionPoints[(i+2)%decisionPoints.length];return <line className="cross" key={`x-${i}`} x1={point.x} y1={point.y} x2={next.x} y2={next.y}/>})}</svg><div className={`orbit-core ${stage!=='IDLE'?'running':''}`}><strong>{stage==='IDLE'?'—':progress}<small>{stage==='IDLE'?'READY':'%'}</small></strong><em>SEARCH</em></div>{decisionCategories.map((x,i)=><span key={x.name} className={`${isRunning?'active':''} ${stage==='COMPLETED'?'done':''}`} style={{left:decisionPoints[i].x-18,top:decisionPoints[i].y-18,'--delay':`${i*.12}s`} as React.CSSProperties}><Icon name={x.icon} size={15}/></span>)}</div><div className="space-summary"><span><b>4</b> 类 · 7 维</span><span><b>512</b> 候选组合</span><span><b>3</b> 优化目标</span></div><div className="optimization-copy"><span>{stage}</span><h2>{stage==='IDLE'?'参数空间已就绪':stage==='COMPLETED'?'推荐参数组合已确定':stage==='VALIDATING'?'正在验证候选方案':'正在搜索候选方案'}</h2><p>{stage==='IDLE'?'启动后将持续生成配置组合并执行方案仿真。':stage==='COMPLETED'?'候选空间已经完成评估与收敛，点击下方按钮查看规划方案及对应性能表现。':`第 ${iteration} / 25 轮迭代：候选配置持续变化，当前正在评估性能、成本和资源约束。`}</p></div><div className="global-progress-head"><span>DESIGN SPACE EXPLORATION</span><b>ITERATION {String(iteration).padStart(2,'0')} / 25</b></div><div className="progress decision-progress"><i style={{width:`${progress}%`}}/></div><div className="optimization-stats"><MiniMetric label="组合候选" value={stage==='IDLE'?0:Math.round(512*progress/100)} unit="/ 512"/><MiniMetric label="方案评估" value={stage==='IDLE'?0:Math.round(286*progress/100)} unit="组"/><MiniMetric label="可行方案" value={stage==='IDLE'?0:Math.round(58*progress/100)} unit="组"/><MiniMetric label="当前最优" value={progress<35?'—':`#${Math.max(1,Math.round(183*progress/100))}`} unit="Solution"/></div><div className="optimization-actions">{stage==='IDLE'&&<button className="primary-action" onClick={onStart}><Icon name="play"/>启动参数寻优</button>}{stage==='COMPLETED'&&<button className="view-results" onClick={onViewResults}>查看规划结果 <Icon name="arrow" size={16}/></button>}</div></section></div>
  </div>
}

function InputWorkspace({section,scenarioKey}:{section:string;scenarioKey:ScenarioKey}){
  const s=scenarios[scenarioKey]
  if(section==='hardware') return <Hardware scenarioKey={scenarioKey}/>
  if(section==='workload') return <Workload scenarioKey={scenarioKey}/>
  if(section==='objective') return <Objectives scenarioKey={scenarioKey}/>
  return <div className="page"><PageTitle eyebrow="INPUT / 01" title="模型与推理软件栈" desc="定义推理对象及其运行环境，能力边界仅描述软件栈可支持范围。" badge="输入配置"/>
    <div className="grid two-one"><Card title="模型描述" subtitle="MODEL PROFILE" icon="cube"><div className="model-hero"><div className="model-symbol">Q3</div><div><span className="muted">当前模型</span><h2>{s.model}</h2><p>{s.modelSize} · MoE Architecture</p></div><span className="verified"><Icon name="check" size={13}/>参数已校验</span></div><div className="spec-grid"><Field label="模型层数" value="80" unit="Layers"/><Field label="Hidden Size" value="8,192"/><Field label="Query Heads" value="64"/><Field label="KV Heads" value="8"/><Field label="Attention" value="GQA / Dense"/><Field label="MoE 结构" value="64 Experts / Top-2"/></div></Card>
    <Card title="数据精度" subtitle="DATA TYPE" icon="layers"><div className="dtype-list"><Dtype name="Weight" value="BF16" pct={82}/><Dtype name="Activation" value="BF16" pct={82}/><Dtype name="KV Cache" value="FP16" pct={68}/></div><div className="info-note">精度配置将影响显存占用、计算吞吐与 KV Cache 容量。</div></Card></div>
    <Card title="推理软件栈" subtitle="SOFTWARE CAPABILITY BOUNDARY" icon="chip"><div className="software-row"><Software name="推理框架" value={s.framework} tag="Serving"/><span className="connector"/><Software name="加速运行时" value={s.runtime} tag="Runtime"/><span className="connector"/><Software name="集合通信库" value={s.comm} tag="Collective"/></div><div className="capabilities"><span>能力边界</span>{['连续批处理','P/D 分离','多维并行','Prefix Cache','KV 分层搬运','异步 I/O'].map((x,i)=><b key={x} className={i<5?'supported':''}><Icon name={i<5?'check':'alert'} size={13}/>{x}</b>)}</div></Card>
  </div>
}

function Hardware({scenarioKey}:{scenarioKey:ScenarioKey}){ const s=scenarios[scenarioKey]; return <div className="page"><PageTitle eyebrow="INPUT / 02" title="硬件与资源拓扑" desc="描述计算、主机、网络与存储资源，以及设备间物理连接关系。" badge={`${s.nodes} 个计算节点`}/><div className="resource-strip"><Metric icon="chip" label="加速设备" value={`${s.gpuCount}`} unit={s.gpu}/><Metric icon="database" label="HBM 总容量" value={scenarioKey==='long'?'65.5':'61.4'} unit="TB"/><Metric icon="network" label="Fabric 带宽" value="25.6" unit="Tbps"/><Metric icon="database" label="存储容量" value="320" unit="TB"/></div><div className="grid topology-grid"><Card title="资源连接拓扑" subtitle="PHYSICAL AFFINITY" icon="network"><Topology/></Card><Card title="资源清单" subtitle="RESOURCE INVENTORY" icon="layers"><div className="inventory"><Inventory title="计算资源" value={`${s.gpuCount} × ${s.gpu}`} meta="BF16 989 TFLOPS · HBM 3.35 TB/s"/><Inventory title="主机资源" value={`${s.nodes} × 2-Socket Server`} meta="DDR5 2 TB · 8 NUMA / Node · PCIe 5.0"/><Inventory title="网络资源" value="400 GbE RDMA Fabric" meta="8 Spine · 32 Leaf · 96 ToR · 1:1"/><Inventory title="存储资源" value="NVMe + Remote KV Store" meta="32 GB/s Read · 4.2M IOPS · QD 256"/></div></Card></div></div> }

function Topology(){return <div className="topology"><div className="top-layer">{['SPINE 01','SPINE 02','SPINE 03','SPINE 04'].map(x=><span key={x}>{x}<small>400G</small></span>)}</div><svg viewBox="0 0 800 125" preserveAspectRatio="none">{[100,300,500,700].flatMap((x,i)=>[140,400,660].map((y,j)=><line key={`${i}-${j}`} x1={x} y1="0" x2={y} y2="125"/>))}</svg><div className="leaf-layer">{['LEAF A','LEAF B','LEAF C'].map(x=><span key={x}>{x}<small>48-Port</small></span>)}</div><div className="rack-layer">{['RACK 01–32','RACK 33–64','RACK 65–96'].map(x=><span key={x}><i/><i/><i/><i/><b>{x}</b></span>)}</div><div className="topology-legend"><i/>400GbE Spine-Link <i/>200GbE ToR-Link</div></div>}

function Workload({scenarioKey}:{scenarioKey:ScenarioKey}){const s=scenarios[scenarioKey];const option=useMemo(()=>({grid:{left:36,right:14,top:24,bottom:26},tooltip:{trigger:'axis',backgroundColor:'#13243a',borderColor:'#263d59',textStyle:{color:'#d9e7f7'}},xAxis:{type:'category',data:s.load.map((_,i)=>`${String(i).padStart(2,'0')}:00`),axisLabel:{color:'#60758d',interval:3,fontSize:10},axisLine:{lineStyle:{color:'#24364c'}},axisTick:{show:false}},yAxis:{type:'value',max:100,axisLabel:{formatter:'{value}%',color:'#60758d',fontSize:10},splitLine:{lineStyle:{color:'#182a3e'}}},series:[{type:'line',data:s.load,smooth:.35,symbol:'none',lineStyle:{width:2,color:'#38bdf8'},areaStyle:{color:{type:'linear',x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:'rgba(56,189,248,.38)'},{offset:1,color:'rgba(56,189,248,.02)'}]}},markPoint:{symbolSize:38,data:[{type:'max',name:'峰值'}],label:{color:'#07111f',fontSize:9}}}]}),[s]);return <div className="page"><PageTitle eyebrow="INPUT / 03" title="Agent 业务负载特征" desc="按请求规模、前缀共享和前缀演化三类特征还原具体业务请求形态。" badge={s.name}/><div className="metric-grid"><MiniMetric label="请求峰值" value={s.peak.toLocaleString()} unit="req/s"/><MiniMetric label="平均请求" value={s.average.toLocaleString()} unit="req/s"/><MiniMetric label="Input Token" value={s.inputTokens} unit="M tok/s"/><MiniMetric label="Output Token" value={s.outputTokens} unit="M tok/s"/><MiniMetric label="会话轮数" value={s.turns} unit="avg"/><MiniMetric label="工具调用" value={s.toolCalls} unit="/ task"/></div><div className="grid workload-grid"><Card title="请求规模特征" subtitle="24H REQUEST PROFILE" icon="activity"><div className="chart-toolbar"><span className="active">Request</span><span>Input Token</span><span>Output Token</span><span>并发会话</span></div><ReactECharts option={option} style={{height:238}}/></Card><Card title="前缀共享特征" subtitle={`REUSE RATE ${s.reuse}%`} icon="layers"><div className="prefix-bars">{s.prefixItems.map(x=><div key={x.label}><div><b>{x.label}</b><small>{x.meta}</small><strong>{x.value}%</strong></div><span><i style={{width:`${x.value}%`}}/></span></div>)}</div></Card></div><Card title="前缀演化特征" subtitle={`AVERAGE GROWTH +${s.prefixGrowth.toLocaleString()} TOKEN / TURN`} icon="network"><div className="timeline">{s.evolution.map((x,i)=><div key={x.round} className={x.type}><span>{x.round}</span><i/><b>{x.action}</b><small>{x.tokens}</small>{i<s.evolution.length-1&&<em/>}</div>)}</div></Card></div>}

function Objectives({scenarioKey}:{scenarioKey:ScenarioKey}){const s=scenarios[scenarioKey];return <div className="page"><PageTitle eyebrow="INPUT / 04" title="目标与约束" desc="定义方案必须满足的服务性能目标与资源边界。" badge="7 项约束已启用"/><div className="grid objective-grid"><Card title="服务性能目标" subtitle="SERVICE LEVEL OBJECTIVE" icon="target"><div className="objective-table"><Objective label="TTFT P95" value={`${s.ttftTarget}`} unit="ms"/><Objective label="TPOT P95" value={`${s.tpotTarget}`} unit="ms"/><Objective label="目标吞吐" value={s.throughputTarget.toFixed(1)} unit="M token/s"/><Objective label="最大 QPS" value={s.maxQps.toLocaleString()} unit="req/s"/><Objective label="目标并发" value={s.maxConcurrency.toLocaleString()} unit="sessions"/></div></Card><Card title="资源与成本约束" subtitle="CAPACITY GUARDRAILS" icon="sliders"><div className="objective-table"><Objective label="设备数量上限" value={`${s.gpuCount}`} unit="Cards"/><Objective label="峰值功耗上限" value={`${Math.round(s.gpuCount*1.05)}`} unit="kW"/><Objective label="年度成本上限" value={`${(s.gpuCount/768*1.2).toFixed(2)}`} unit="亿元"/><div className="constraint-health"><Icon name="check"/><div><b>约束可行性检查通过</b><small>当前资源池存在 46 个可行候选方案</small></div></div></div></Card></div></div>}

function Tunables(){const [cat,setCat]=useState('服务级调度');const cats=['服务级调度','推理引擎调度','并行策略','KV 复用与缓存策略','部署拓扑与资源亲和','KV 资源池与分层放置','数据流编排'];return <div className="page"><PageTitle eyebrow="TUNABLES / 05" title="参数搜索空间" desc="配置四大类、七个全局参数维度的候选范围。" badge="4 GROUPS · 7 DIMENSIONS"/><div className="tunable-layout"><div className="category-list">{cats.map((x,i)=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}><span>0{i+1}</span>{x}<Icon name="arrow" size={14}/></button>)}</div><div><Card title={cat} subtitle="SEARCH RANGE" icon="sliders"><TunableContent cat={cat}/></Card></div></div></div>}

function TunableContent({cat}:{cat:string}){const rows:Record<string,[string,string,string][]>={'服务级调度':[['实例选择','Load-aware','RR / Affinity / Load-aware'],['P-D Pairing','Topology-aware','Static / Load / Topology-aware'],['Admission Control','Enabled','On / Off'],['请求优先级','SLO-aware','FIFO / SLO-aware']],'推理引擎调度':[['max_num_seqs','128','64 — 512'],['max_num_batched_tokens','16,384','8K — 64K'],['实例内调度','Continuous Batching','Continuous / Priority'],['Chunked Prefill','Enabled · 4K','2K — 16K']],并行策略:[['Tensor Parallel','8','4 — 16'],['Data Parallel','4','2 — 16'],['Pipeline Parallel','1','1 — 4'],['Expert Parallel','8','4 — 16']],'KV 复用与缓存策略':[['Prefix Cache','Enabled','On / Off'],['缓存准入','Reuse-aware','All / Reuse-aware'],['淘汰策略','Cost-aware LRU','LRU / LFU / Cost-aware'],['Prefetch','Adaptive','Off / Static / Adaptive']],'部署拓扑与资源亲和':[['部署模式','P-D 分离','共享池 / P-D 分离'],['Prefill 节点','64','32 — 128'],['Decode 节点','32','16 — 96'],['实例放置','Topology-aware','Local / Topology-aware']],'KV 资源池与分层放置':[['KV 管理组件','LMCache','Native / LMCache / HiCache'],['池化范围','Global','Local / Cluster / Global'],['分布式存储','Mooncake Store','Local / Mooncake / 3FS'],['分层放置迁移','HBM ↔ DDR ↔ SSD','2-tier / 3-tier / Global']],'数据流编排':[['Transfer Backend','RDMA Direct','UB / RDMA / NVMe-oF'],['Slice 粒度','Adaptive','Static / Adaptive'],['Rail Mapping','Topology-aware','Single / Multi-Rail'],['传输优先级','SLO-aware','FIFO / SLO-aware']]};return <div className="tunable-table"><div className="tunable-head"><span>参数</span><span>当前值</span><span>寻优范围</span></div>{rows[cat].map(r=><div key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><small>{r[2]}</small></div>)}</div>}

function Results({stage,progress,scenarioKey}:{stage:Stage;progress:number;scenarioKey:ScenarioKey}){const s=scenarios[scenarioKey];if(stage!=='COMPLETED')return <div className="page result-loading"><PageTitle eyebrow="SIMULATION / PLANNING" title="算存网一体化规划寻优" desc="正在评估服务控制、推理执行、资源布局与数据移动四大类七维决策空间。" badge={stageText[stage]}/><div className="optimizer"><div className="optimizer-orbit"><span>{progress}<small>%</small></span><i/><i/><i/></div><h2>{stage==='IDLE'?'等待启动仿真规划':stageText[stage]}</h2><p>{stage==='IDLE'?'确认输入与可调参数后，点击左侧“开始仿真规划”。':'基于当前 Agent 负载与 SLO 约束评估可行规划方案'}</p><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="search-stats"><MiniMetric label="候选方案" value={Math.round(512*progress/100)} unit="/ 512"/><MiniMetric label="已评估" value={Math.round(286*progress/100)} unit="组"/><MiniMetric label="满足 SLO" value={Math.round(58*progress/100)} unit="组"/><MiniMetric label="当前最优" value={progress<35?'—':`#${Math.max(1,Math.round(183*progress/100))}`} unit="Solution"/></div><div className="stage-flow">{stages.map(x=><div key={x} className={`${stages.indexOf(x)<stages.indexOf(stage)?'done':''} ${x===stage?'active':''}`}><i>{stages.indexOf(x)<stages.indexOf(stage)?<Icon name="check" size={14}/>:stages.indexOf(x)+1}</i><span>{stageText[x]}</span></div>)}</div></div></div>;
return <div className="page result-page"><div className="result-hero"><div><span className="success-label"><Icon name="check" size={14}/>PLANNING COMPLETED</span><h2>推荐方案 · Solution #183</h2><p>{s.name} · 满足全部 SLO 与资源约束 · 综合评分 92.8</p></div><div className="hero-score"><strong>92.8</strong><span>综合评分</span></div><div className="hero-kpis"><div><small>TTFT P95</small><b>{s.ttftResult} <i>ms</i></b></div><div><small>TPOT P95</small><b>{s.tpotResult} <i>ms</i></b></div><div><small>吞吐</small><b>{s.throughputResult.toFixed(1)} <i>M tok/s</i></b></div><span className="pass-pill">ALL SLO PASS</span></div></div><div className="result-flow"><section className="result-section"><ResultSectionHead index="01" eyebrow="RECOMMENDED PLAN" title="推荐规划方案" desc="明确实例部署、调度路由、KV 资源池和网络数据流配置。"/><Plan s={s}/></section><section className="result-section"><ResultSectionHead index="02" eyebrow="PERFORMANCE VALIDATION" title="方案性能表现" desc="验证服务性能目标，并给出各类资源利用率和运行余量。"/><Performance s={s}/></section><section className="result-section"><ResultSectionHead index="03" eyebrow="BOTTLENECK & ALTERNATIVES" title="瓶颈与寻优结论" desc="定位主要瓶颈、分析参数敏感性，并保留可行候选方案对比。"/><Bottleneck s={s}/></section></div></div>}

function ResultSectionHead({index,eyebrow,title,desc}:{index:string;eyebrow:string;title:string;desc:string}){return <div className="result-section-head"><span>{index}</span><div><small>{eyebrow}</small><h2>{title}</h2><p>{desc}</p></div></div>}

function Plan({s}:{s:(typeof scenarios)[ScenarioKey]}){
  const hbmTotal=s.gpuCount*64/1024
  const prefillCards=s.prefillNodes*8
  const decodeCards=s.decodeNodes*8
  const prefillPct=Math.round(s.prefillNodes/(s.prefillNodes+s.decodeNodes)*100)
  const kvStack=getKvResourceStack(s)
  return <div className="results-grid">
    <Card title="计算资源与 P/D 部署" subtitle="NODE & INSTANCE PLANNING" icon="chip"><div className="plan-primary"><span><small>Prefill 节点</small><b>{s.prefillNodes}</b><i>{s.prefillInstances} 实例组 · {prefillCards} 卡</i></span><span><small>Decode 节点</small><b>{s.decodeNodes}</b><i>{s.decodeInstances} 实例组 · {decodeCards} 卡</i></span><span><small>单实例组</small><b>{s.nodesPerInstance}</b><i>节点/组 · 每节点 8 卡</i></span></div><div className="pd-allocation"><div><span>Prefill <b>{prefillPct}%</b></span><span>Decode <b>{100-prefillPct}%</b></span></div><i><b style={{width:`${prefillPct}%`}}/><b style={{width:`${100-prefillPct}%`}}/></i></div><div className="instance-note">共 {s.nodes} 节点 / {s.gpuCount} 卡{s.reservedNodes>0?` · ${s.reservedNodes} 节点作为部署余量`:''}；实例组按模型并行规模折算。</div></Card>
    <Card title="服务调度与引擎执行" subtitle="SERVICE CONTROL / INFERENCE EXECUTION" icon="sliders"><div className="key-value"><p><span>引擎调度</span><b>Continuous Batching</b></p><p><span>Chunked Prefill</span><b>Enabled / 4K</b></p><p><span>服务级路由</span><b>Load-aware · Cache-aware</b></p><p><span>准入控制</span><b className="green">Enabled</b></p></div></Card>
    <div className="plan-wide"><Card title="KV 资源池与分层放置规划" subtitle="POOL STRATEGY / ESTIMATED DEMAND / PLANNED CAPACITY" icon="database"><div className="kv-pool-strategy"><span><small>KV 管理层</small><b>{kvStack.split(' + ')[0]}</b></span><span><small>池化范围</small><b>Cluster + Global</b></span><span><small>分布式存储</small><b>Mooncake Store</b></span><span><small>放置与迁移</small><b>HBM ↔ DDR ↔ SSD</b></span></div><div className="capacity-plan-grid"><CapacityPlan label="HBM Pool" demand={s.hbmDemandTB} total={hbmTotal} scope="模型常驻、运行时与热 KV"/><CapacityPlan label="DDR Pool" demand={s.ddrDemandTB} total={s.ddrTB} scope="Warm KV · 跨节点共享"/><CapacityPlan label="Local SSD Pool" demand={s.localSsdDemandTB} total={s.localSsdTB} scope="集群内冷 KV 与回源"/><CapacityPlan label="Remote SSD Pool" demand={s.remoteSsdDemandTB} total={s.remoteSsdTB} scope="跨集群长尾 KV"/></div><div className="sizing-note"><Icon name="activity" size={14}/><span>需求估算：模型常驻与运行时占用 + 峰值并发 KV + 分层承接量；规划总量按节点/盘组规格向上取整并保留运行余量。</span></div></Card></div>
    <div className="plan-wide"><Card title="规划后算存网拓扑" subtitle="P/D DEPLOYMENT · CAPACITY · BOTTLENECK LOCATION" icon="network"><PlanningNetworkTopology scenario={s}/></Card></div>
  </div>
}

function CapacityPlan({label,demand,total,scope}:{label:string;demand:number;total:number;scope:string}){const pct=Math.round(demand/total*100);return <div className={`capacity-plan ${pct>=88?'near-limit':''}`}><div><small>{label}</small><b>{demand.toFixed(1)} <i>/ {total.toFixed(1)} TB</i></b><span>{pct}% USED · {Math.round((total-demand)*10)/10} TB 余量</span></div><em><i style={{width:`${Math.min(100,pct)}%`}}/></em><p>{scope}</p></div>}

function PlanningNetworkTopology({scenario:s}:{scenario:Scenario}){const hbmTotal=s.gpuCount*64/1024;const bottleneck=s.key==='rag'?'fabric':s.key==='long'?'hbm':'decode';const primaryFlow=s.key==='rag'?'Prefix KV / P-D Handoff':s.key==='long'?'Long KV / Tier Migration':'Branch KV / Tool Context';const backendPlan=s.key==='coding'?'UB Direct · RDMA Direct':'RDMA Direct · NVMe-oF';const fabricDemandTbps=1.6*s.fabricUtilization/100;return <div className="planning-topology"><div className="orchestration-summary"><span><small>数据流</small><b>{primaryFlow}</b></span><span><small>Transfer Backend</small><b>{backendPlan}</b></span><span><small>Rail 规划</small><b>4 / 4 Rails · NUMA-aware</b></span><span><small>调度与容错</small><b>Priority-aware · Dynamic Remap</b></span></div><svg viewBox="0 0 1120 410" role="img" aria-label="规划后 P D 节点与 HBM DDR SSD 资源池拓扑">
  <g className={`plan-fabric ${bottleneck==='fabric'?'hot':''}`}><rect x="425" y="14" width="270" height="42" rx="6"/><text x="560" y="32">DUAL-PLANE 400GbE RDMA FABRIC</text><text x="560" y="47" className="sub">需求 {fabricDemandTbps.toFixed(2)} / 1.60 Tbps · 4 / 4 Rails</text></g><path className="plan-link" d="M560 56V78M280 78H840M280 78V97M840 78V97"/>
  <g className="plan-cluster"><rect x="25" y="97" width="510" height="238" rx="8"/><rect x="585" y="97" width="510" height="238" rx="8"/><text x="45" y="120">CLUSTER A · {Math.floor(s.nodes/2)} NODES</text><text x="605" y="120">CLUSTER B · {Math.ceil(s.nodes/2)} NODES</text></g>
  <g className="plan-compute"><rect className="prefill" x="48" y="139" width="210" height="58" rx="5"/><rect className={`decode ${bottleneck==='decode'?'hot':''}`} x="278" y="139" width="234" height="58" rx="5"/><rect className="prefill" x="608" y="139" width="210" height="58" rx="5"/><rect className={`decode ${bottleneck==='decode'?'hot':''}`} x="838" y="139" width="234" height="58" rx="5"/><text x="68" y="163">PREFILL · {s.prefillNodes/2} Nodes</text><text x="68" y="181" className="sub">{s.prefillInstances/2} Groups · {(s.prefillNodes/2)*8} Cards</text><text x="298" y="163">DECODE · {s.decodeNodes/2} Nodes</text><text x="298" y="181" className="sub">{s.decodeInstances/2} Groups · {(s.decodeNodes/2)*8} Cards</text><text x="628" y="163">PREFILL · {s.prefillNodes/2} Nodes</text><text x="628" y="181" className="sub">{s.prefillInstances/2} Groups · {(s.prefillNodes/2)*8} Cards</text><text x="858" y="163">DECODE · {s.decodeNodes/2} Nodes</text><text x="858" y="181" className="sub">{s.decodeInstances/2} Groups · {(s.decodeNodes/2)*8} Cards</text></g>
  <g className={`plan-pool hbm ${bottleneck==='hbm'?'hot':''}`}><rect x="48" y="213" width="464" height="45" rx="5"/><rect x="608" y="213" width="464" height="45" rx="5"/><text x="66" y="232">L0 · HBM POOL</text><text x="494" y="232" textAnchor="end">{(s.hbmDemandTB/2).toFixed(1)} / {(hbmTotal/2).toFixed(1)} TB</text><text x="66" y="248" className="sub">模型常驻 · Runtime · Hot KV</text><text x="626" y="232">L0 · HBM POOL</text><text x="1054" y="232" textAnchor="end">{(s.hbmDemandTB/2).toFixed(1)} / {(hbmTotal/2).toFixed(1)} TB</text><text x="626" y="248" className="sub">模型常驻 · Runtime · Hot KV</text></g>
  <g className="plan-pool lower"><rect x="48" y="272" width="220" height="43" rx="5"/><rect x="292" y="272" width="220" height="43" rx="5"/><rect x="608" y="272" width="220" height="43" rx="5"/><rect x="852" y="272" width="220" height="43" rx="5"/><text x="62" y="291">L1 DDR · {(s.ddrDemandTB/2).toFixed(1)} / {s.ddrTB/2} TB</text><text x="306" y="291">L2 SSD · {(s.localSsdDemandTB/2).toFixed(1)} / {s.localSsdTB/2} TB</text><text x="622" y="291">L1 DDR · {(s.ddrDemandTB/2).toFixed(1)} / {s.ddrTB/2} TB</text><text x="866" y="291">L2 SSD · {(s.localSsdDemandTB/2).toFixed(1)} / {s.localSsdTB/2} TB</text><text x="62" y="306" className="sub">跨节点 Warm KV</text><text x="306" y="306" className="sub">集群内 Cold KV</text><text x="622" y="306" className="sub">跨节点 Warm KV</text><text x="866" y="306" className="sub">集群内 Cold KV</text></g>
  <g className="planned-flow"><path className="handoff" d="M255 168C420 112 700 112 840 168"/><text x="560" y="107">P/D Handoff · Direct RDMA</text><path className="prefetch" d="M560 336C560 286 740 276 840 213"/><text className="prefetch-label" x="738" y="326">Cache Prefetch · NVMe-oF</text></g>
  <path className="plan-link remote" d="M402 315V350H470M718 315V350H650"/><g className="plan-remote"><rect x="470" y="336" width="180" height="54" rx="6"/><text x="560" y="357">L3 · REMOTE SSD</text><text x="560" y="375">{s.remoteSsdDemandTB} / {s.remoteSsdTB} TB</text></g>
  </svg><div className="planning-legend"><span><i className="need"/>前值为估算需求</span><span><i className="capacity"/>后值为规划总量</span><span><i className="flow"/>规划数据流映射</span><span><i className="hot"/>橙色标识当前主要瓶颈</span></div></div>}

function Performance({s}:{s:(typeof scenarios)[ScenarioKey]}){const hbmTotal=s.gpuCount*64/1024;const util=[['A5 Compute',84,'#38bdf8'],['HBM',Math.round(s.hbmDemandTB/hbmTotal*100),'#818cf8'],['DDR Pool',Math.round(s.ddrDemandTB/s.ddrTB*100),'#a78bfa'],['RDMA Fabric',s.fabricUtilization,'#2dd4bf'],['SSD I/O',Math.round(Math.max(s.localSsdDemandTB/s.localSsdTB,s.remoteSsdDemandTB/s.remoteSsdTB)*100),'#22c55e']];const maxUtil=Math.max(...util.map(x=>Number(x[1])));return <div><div className="grid perf-grid"><Card title="服务性能与 SLO" subtitle="ALL TARGETS PASSED" icon="target"><div className="slo-table"><div><span>指标</span><span>目标</span><span>仿真结果</span><span>状态</span></div>{[['TTFT P95',`< ${s.ttftTarget} ms`,`${s.ttftResult} ms`],['TPOT P95',`< ${s.tpotTarget} ms`,`${s.tpotResult} ms`],['Throughput',`> ${s.throughputTarget.toFixed(1)} M tok/s`,`${s.throughputResult.toFixed(1)} M tok/s`],['Availability','99.99%','99.995%']].map(r=><div key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><strong>{r[2]}</strong><i>PASS</i></div>)}</div></Card><Card title="资源利用率与余量" subtitle={`MIN HEADROOM ${100-maxUtil}%`} icon="activity"><div className="util-list">{util.map(x=><div key={String(x[0])}><span>{x[0]}</span><b><i style={{width:`${x[1]}%`,background:String(x[2])}}/></b><strong>{x[1]}%</strong></div>)}</div></Card></div><div className="metric-grid result-metrics"><MiniMetric label="E2E P95" value={(s.ttftResult/1000+1.9).toFixed(2)} unit="s"/><MiniMetric label="最大 QPS" value={s.maxQps.toLocaleString()} unit="req/s"/><MiniMetric label="最大并发" value={s.maxConcurrency.toLocaleString()} unit="sessions"/><MiniMetric label="SLO 达标率" value="99.96" unit="%"/><MiniMetric label="KV 命中率" value={s.kvHitRate.toFixed(1)} unit="%"/><MiniMetric label="超时率" value="0.04" unit="%"/></div></div>}

const bottleneckProfiles={
  rag:{active:'Fabric',prefill:78,decode:82,ssd:72,signal:'1.41 / 1.60 Tbps · 峰值利用率 88%',mechanism:'P/D Handoff 与远端 Prefix KV Prefetch 竞争跨集群 Rail',judgement:'网络余量先于计算耗尽，继续扩容实例将首先放大 KV 传输等待',secondary:'HBM 40.8 / 48.0 TB · 85% USED',sens:[['Rail 与流映射',91,'+21.6%'],['P:D 节点配比',84,'+16.8%'],['HBM 容量',69,'+10.9%'],['Prefix 路由亲和',57,'+8.1%'],['Slice 并发度',45,'+5.7%']]},
  long:{active:'HBM',prefill:85,decode:76,ssd:85,signal:'58.2 / 64.0 TB · 峰值占用 91%',mechanism:'长上下文 KV 持续增长，HBM 淘汰向 DDR / SSD 下沉并触发回源',judgement:'容量压力已传导为迁移与 Prefetch 开销，TTFT 对分层命中最敏感',secondary:'SSD Prefetch 13.6 / 16.0 GB/s · 85% USED',sens:[['HBM 容量',94,'+22.7%'],['Prefetch 策略',82,'+17.1%'],['KV 分层放置',74,'+13.8%'],['P:D 节点配比',61,'+9.4%'],['Chunk 大小',48,'+6.3%']]},
  coding:{active:'Decode',prefill:73,decode:92,ssd:68,signal:'Decode 峰值利用率 92% · 排队 P95 31 ms',mechanism:'多轮生成与工具回调延长 Decode 占用，分支会话集中到热点实例',judgement:'瓶颈来自 Decode 配比与服务级路由，不是集群总算力不足',secondary:'KV Transfer 1.30 / 1.60 Tbps · 81% USED',sens:[['P:D 节点配比',92,'+20.5%'],['Decode Batch Tokens',84,'+16.2%'],['请求路由亲和',71,'+11.8%'],['KV 传输并发',62,'+8.9%'],['Admission Control',43,'+5.4%']]},
} as const

function Bottleneck({s}:{s:(typeof scenarios)[ScenarioKey]}){const profile=bottleneckProfiles[s.key];const sens=profile.sens;const baseCost=s.gpuCount/768*1.08;const rows=[['推荐方案','PASS',s.gpuCount,`¥ ${baseCost.toFixed(2)} 亿`,s.throughputResult.toFixed(1),'综合最优'],['最小资源','PASS',s.gpuCount-64,`¥ ${(baseCost*.9).toFixed(2)} 亿`,(s.throughputResult*.84).toFixed(1),'资源最少'],['最大吞吐','PASS',s.gpuCount+128,`¥ ${(baseCost*1.17).toFixed(2)} 亿`,(s.throughputResult*1.25).toFixed(1),'吞吐最高']];return <div><div className="grid bottleneck-grid"><Card title="瓶颈位置与影响链路" subtitle="BOTTLENECK EVIDENCE / IMPACT PATH" icon="alert"><BottleneckPath s={s}/><div className="bottleneck-evidence"><span><small>触发信号</small><b>{profile.signal}</b></span><span><small>影响链路</small><b>{profile.mechanism}</b></span><span><small>规划判断</small><b>{profile.judgement}</b></span></div><div className="bottleneck-secondary"><span>次要瓶颈</span><b>{s.bottleneckSub}</b><i>{profile.secondary}</i></div></Card><Card title="场景参数敏感性" subtitle="SCENARIO-SPECIFIC IMPACT" icon="sliders"><div className="sensitivity">{sens.map(x=><div key={String(x[0])}><span>{x[0]}</span><b><i style={{width:`${x[1]}%`}}/></b><strong>{x[2]}</strong></div>)}</div></Card></div><Card title="Top-K 候选方案" subtitle="FEASIBLE SOLUTIONS" icon="layers"><div className="candidate-table"><div><span>方案</span><span>SLO</span><span>GPU/NPU</span><span>年度成本</span><span>吞吐</span><span>主要特点</span></div>{rows.map((r,i)=><div className={i===0?'recommended':''} key={String(r[0])}><b>{i===0&&<i>★</i>}{r[0]}</b><span className="pass">{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span><strong>{r[4]} M tok/s</strong><span>{r[5]}</span></div>)}</div></Card></div>}

function BottleneckPath({s}:{s:Scenario}){const profile=bottleneckProfiles[s.key];const hbm=Math.round(s.hbmDemandTB/(s.gpuCount*64/1024)*100);const ddr=Math.round(s.ddrDemandTB/s.ddrTB*100);const nodes=[['Prefill',profile.prefill],['Decode',profile.decode],['HBM',hbm],['DDR',ddr],['Fabric',s.fabricUtilization],['SSD I/O',profile.ssd]];return <div className="bottleneck-visual"><div className="bottleneck-callout"><span>PRIMARY BOTTLENECK</span><b>{s.bottleneck}</b><small>峰值窗口中最先逼近规划阈值的资源或调度环节</small></div><div className="bottleneck-path">{nodes.map((x,i)=><div key={String(x[0])} className={x[0]===profile.active?'active':''}><span>{x[0]}</span><b>{x[1]}%</b><i><em style={{height:`${Math.min(100,Number(x[1]))}%`}}/></i>{i<nodes.length-1&&<small/>}</div>)}</div></div>}

function PageTitle({eyebrow,title,desc,badge}:{eyebrow:string;title:string;desc:string;badge:string}){return <div className="page-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div><b>{badge}</b></div>}
function Card({title,subtitle,icon,children}:{title:string;subtitle:string;icon:string;children:React.ReactNode}){return <section className="card"><div className="card-head"><span><Icon name={icon}/></span><div><h3>{title}</h3><p>{subtitle}</p></div><button>•••</button></div><div className="card-body">{children}</div></section>}
function Field({label,value,unit}:{label:string;value:string;unit?:string}){return <label className="field"><span>{label}</span><div><b>{value}</b>{unit&&<small>{unit}</small>}</div></label>}
function Dtype({name,value,pct}:{name:string;value:string;pct:number}){return <div className="dtype"><span>{name}</span><b>{value}</b><i><em style={{width:`${pct}%`}}/></i></div>}
function Software({name,value,tag}:{name:string;value:string;tag:string}){return <div className="software"><span>{tag}</span><Icon name="chip"/><small>{name}</small><b>{value}</b></div>}
function Metric({icon,label,value,unit}:{icon:string;label:string;value:string;unit:string}){return <div className="resource-metric"><span><Icon name={icon}/></span><div><small>{label}</small><b>{value}</b><i>{unit}</i></div></div>}
function MiniMetric({label,value,unit}:{label:string;value:string|number;unit:string}){return <div className="mini-metric"><span>{label}</span><b>{value}</b><small>{unit}</small></div>}
function Inventory({title,value,meta}:{title:string;value:string;meta:string}){return <div className="inventory-item"><i/><div><span>{title}</span><b>{value}</b><small>{meta}</small></div><Icon name="arrow" size={15}/></div>}
function Objective({label,value,unit}:{label:string;value:string;unit:string}){return <div className="objective"><button className="switch on"><i/></button><b>{label}</b><span>{value}<small>{unit}</small></span></div>}

export default App
